# change the followings to match your Github username and repo name
baseurl: "" # the name of your github repo
url: "https://harrywang.github.io" # the url of your github pages

# site information used in page title, meta data etc.
title: "harrywang.me"
description: Harry Wang's Personal Website

# color theme for links
theme-color: indigo # indigo|yellow|pink|green|stone|

# homepage information
author: Harry Wang
author-bio: professor / entrepreneur / artisan  # change to false to hide
author-image: harrywang.jpg  # file must be in the /assets/img/ folder

# navigation menu
show-nav-menu: true

nav-menu:
- text: About
  permalink: about
- text: Blog
  permalink: blog

# use false to turn off any social media links
twitter: false
eth: https://opensea.io/harryjwang.eth
facebook: false
instagram: false
github: https://github.com/harrywang
linkedin: https://www.linkedin.com/in/harryjwang/
medium: https://medium.com/@harrywang
rss: /feed.xml
google-scholar: false
email: "mailto:hjwang@udel.edu"

# footer information
footer-msg: "Powered by Tailpages"
footer-msg-link: https://github.com/harrywang/tailpages

# google analytics
google-analytics: G-QWDZHEK3XK

# jekyll plugins - no need to change
plugins:
    - jekyll-seo-tag
    - jekyll-feed